/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 18-feb.-2019 9:25:07 p.m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `alojamientos` CASCADE
;

DROP TABLE IF EXISTS `atractivos` CASCADE
;

DROP TABLE IF EXISTS `avatares` CASCADE
;

DROP TABLE IF EXISTS `departamentos` CASCADE
;

DROP TABLE IF EXISTS `fotos` CASCADE
;

DROP TABLE IF EXISTS `logros` CASCADE
;

DROP TABLE IF EXISTS `logros_objetivos` CASCADE
;

DROP TABLE IF EXISTS `municipios` CASCADE
;

DROP TABLE IF EXISTS `objetivos` CASCADE
;

DROP TABLE IF EXISTS `restaurantes` CASCADE
;

DROP TABLE IF EXISTS `rutas` CASCADE
;

DROP TABLE IF EXISTS `usuarios` CASCADE
;

DROP TABLE IF EXISTS `usuarios_logros` CASCADE
;

/* Create Tables */

CREATE TABLE `alojamientos`
(
	`id_alojamiento` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_alojamiento` VARCHAR(250) NOT NULL,
	`foto_alojamiento` VARCHAR(250) NOT NULL,
	`telefono_alojamiento` VARCHAR(50) NOT NULL,
	`direccion_Alojamiento` VARCHAR(50) NOT NULL,
	`id_municipio` BIGINT NULL,
	`latitud_alojamiento` DOUBLE(10,2) NOT NULL,
	`longitud_alojamiento` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_alojamiento` PRIMARY KEY (`id_alojamiento` ASC)
)

;

CREATE TABLE `atractivos`
(
	`id_atractivo` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_atractivo` VARCHAR(50) NOT NULL,
	`longitud_Atractivo` DOUBLE(10,6) NOT NULL,
	`latitud_atractivo` DOUBLE(10,6) NOT NULL,
	`descripcion_atractivo` TEXT NOT NULL,
	`id_instagram` INT NOT NULL,
	`id_municipio` BIGINT NOT NULL,
	`id_ruta` BIGINT NOT NULL,
	CONSTRAINT `PK_atractivo` PRIMARY KEY (`id_atractivo` ASC)
)

;

CREATE TABLE `avatares`
(
	`id_avatar` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_avatar` VARCHAR(50) NOT NULL,
	`url_avatar` VARCHAR(250) NOT NULL,
	CONSTRAINT `PK_avatar` PRIMARY KEY (`id_avatar` ASC)
)

;

CREATE TABLE `departamentos`
(
	`id_departamento` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_departamento` VARCHAR(100) NOT NULL,
	`longitud_departamento` DOUBLE(10,6) NOT NULL,
	`latitud_departamento` DOUBLE(10,6) NOT NULL,
	CONSTRAINT `PK_departamento` PRIMARY KEY (`id_departamento` ASC)
)

;

CREATE TABLE `fotos`
(
	`id_foto` BIGINT NOT NULL AUTO_INCREMENT,
	`id_usuario` BIGINT NOT NULL,
	`id_municipio` BIGINT NOT NULL,
	`url_foto` VARCHAR(255) NOT NULL,
	CONSTRAINT `PK_foto` PRIMARY KEY (`id_foto` ASC)
)

;

CREATE TABLE `logros`
(
	`id_logro` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_logro` VARCHAR(50) NOT NULL,
	`descripcion_logro` TEXT NOT NULL,
	`insignia_logro` VARCHAR(250) NOT NULL,
	`estado_logro` INT NOT NULL,
	CONSTRAINT `PK_logros` PRIMARY KEY (`id_logro` ASC)
)

;

CREATE TABLE `logros_objetivos`
(
	`id_logro_objetivo` BIGINT NOT NULL AUTO_INCREMENT,
	`id_logro` BIGINT NULL,
	`estado` INT NOT NULL,
	`id_objetivo` BIGINT NULL,
	CONSTRAINT `PK_logroObjetivo` PRIMARY KEY (`id_logro_objetivo` ASC)
)

;

CREATE TABLE `municipios`
(
	`id_municipio` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_municipio` VARCHAR(50) NOT NULL,
	`longitud_municipio` DOUBLE(10,6) NOT NULL,
	`latitud_municipio` DOUBLE(10,6) NOT NULL,
	`id_departamento` BIGINT NOT NULL,
	`descripcion_basica_municipio` TEXT NOT NULL,
	`descripcionLargaMunicipio` TEXT NOT NULL,
	`id_instagram` VARCHAR(250) NOT NULL,
	`foto_municipio` VARCHAR(250) NOT NULL,
	CONSTRAINT `PK_municipio` PRIMARY KEY (`id_municipio` ASC)
)

;

CREATE TABLE `objetivos`
(
	`id_objetivo` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_objetivo` VARCHAR(50) NOT NULL,
	`descripcion_objetivo` TEXT NOT NULL,
	CONSTRAINT `PK_objetivo` PRIMARY KEY (`id_objetivo` ASC)
)

;

CREATE TABLE `restaurantes`
(
	`id_restaurante` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_restaurante` VARCHAR(250) NOT NULL,
	`foto_restaurante` VARCHAR(250) NOT NULL,
	`direccion_restaurante` VARCHAR(250) NOT NULL,
	`telefono_restaurante` VARCHAR(50) NOT NULL,
	`id_municipio` BIGINT NULL,
	`latitud_restaurante` DOUBLE(10,6) NOT NULL,
	`longitud_restaurante` DOUBLE(10,6) NOT NULL,
	CONSTRAINT `PK_restaurante` PRIMARY KEY (`id_restaurante` ASC)
)

;

CREATE TABLE `rutas`
(
	`id_ruta` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_ruta` VARCHAR(50) NOT NULL,
	`descripcion_ruta` TEXT NOT NULL,
	CONSTRAINT `PK_ruta` PRIMARY KEY (`id_ruta` ASC)
)

;

CREATE TABLE `usuarios`
(
	`id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
	`nombre_usuario` VARCHAR(50) NOT NULL,
	`apellido_usuario` VARCHAR(50) NOT NULL,
	`correo_usuario` VARCHAR(250) NOT NULL,
	`contrasena_usuario` VARCHAR(50) NOT NULL,
	`apodo_usuario` VARCHAR(50) NOT NULL,
	`telefono_usuario` VARCHAR(50) NULL,
	`id_avatar` BIGINT NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`id_usuario` ASC)
)

;

CREATE TABLE `usuarios_logros`
(
	`id_usuario_logro` BIGINT NOT NULL AUTO_INCREMENT,
	`id_usuario` BIGINT NOT NULL,
	`estado_usuaro_logro` INT NOT NULL,
	`id_logro` BIGINT NOT NULL,
	CONSTRAINT `PK_usuarioLogro` PRIMARY KEY (`id_usuario_logro` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `alojamientos` 
 ADD INDEX `IXFK_alojamientos_municipios` (`id_municipio` ASC)
;

ALTER TABLE `atractivos` 
 ADD INDEX `IXFK_atractivos_municipios` (`id_municipio` ASC)
;

ALTER TABLE `atractivos` 
 ADD INDEX `IXFK_atractivos_rutas` (`id_ruta` ASC)
;

ALTER TABLE `fotos` 
 ADD INDEX `IXFK_fotos_municipios` (`id_municipio` ASC)
;

ALTER TABLE `fotos` 
 ADD INDEX `IXFK_fotos_usuarios` (`id_usuario` ASC)
;

ALTER TABLE `logros_objetivos` 
 ADD INDEX `IXFK_logroObjetivo_logros` (`id_logro` ASC)
;

ALTER TABLE `logros_objetivos` 
 ADD INDEX `IXFK_logroObjetivo_objetivos` (`id_objetivo` ASC)
;

ALTER TABLE `municipios` 
 ADD INDEX `IXFK_municipios_departamentos` (`id_departamento` ASC)
;

ALTER TABLE `restaurantes` 
 ADD INDEX `IXFK_restaurantes_municipios` (`id_municipio` ASC)
;

ALTER TABLE `usuarios` 
 ADD INDEX `IXFK_usuarios_avatares` (`id_avatar` ASC)
;

ALTER TABLE `usuarios_logros` 
 ADD INDEX `IXFK_usuarioLogro_logros` (`id_logro` ASC)
;

ALTER TABLE `usuarios_logros` 
 ADD INDEX `IXFK_usuarioLogro_usuarios` (`id_usuario` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `alojamientos` 
 ADD CONSTRAINT `FK_alojamientos_municipios`
	FOREIGN KEY (`id_municipio`) REFERENCES `municipios` (`id_municipio`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `atractivos` 
 ADD CONSTRAINT `FK_atractivos_municipios`
	FOREIGN KEY (`id_municipio`) REFERENCES `municipios` (`id_municipio`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `atractivos` 
 ADD CONSTRAINT `FK_atractivos_rutas`
	FOREIGN KEY (`id_ruta`) REFERENCES `rutas` (`id_ruta`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `fotos` 
 ADD CONSTRAINT `FK_fotos_municipios`
	FOREIGN KEY (`id_municipio`) REFERENCES `municipios` (`id_municipio`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `fotos` 
 ADD CONSTRAINT `FK_fotos_usuarios`
	FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id_usuario`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `logros_objetivos` 
 ADD CONSTRAINT `FK_logroObjetivo_logros`
	FOREIGN KEY (`id_logro`) REFERENCES `logros` (`id_logro`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `logros_objetivos` 
 ADD CONSTRAINT `FK_logroObjetivo_objetivos`
	FOREIGN KEY (`id_objetivo`) REFERENCES `objetivos` (`id_objetivo`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `municipios` 
 ADD CONSTRAINT `FK_municipios_departamentos`
	FOREIGN KEY (`id_departamento`) REFERENCES `departamentos` (`id_departamento`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `restaurantes` 
 ADD CONSTRAINT `FK_restaurantes_municipios`
	FOREIGN KEY (`id_municipio`) REFERENCES `municipios` (`id_municipio`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `usuarios` 
 ADD CONSTRAINT `FK_usuarios_avatares`
	FOREIGN KEY (`id_avatar`) REFERENCES `avatares` (`id_avatar`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `usuarios_logros` 
 ADD CONSTRAINT `FK_usuarioLogro_logros`
	FOREIGN KEY (`id_logro`) REFERENCES `logros` (`id_logro`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `usuarios_logros` 
 ADD CONSTRAINT `FK_usuarioLogro_usuarios`
	FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id_usuario`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1
; 
